#!/bin/bash
########################################################################
#
# dyndnslogin
# Automate login to prevent account expiration
#
########################################################################

########################################################################
# DynDNS Settings (default-value, overwrite with $1 and $2)
DEFAULT_USERNAME="`cat dyndnslogin-data | grep user | cut -f 2 -d :`"
DEFAULT_PASSWORD="`cat dyndnslogin-data | grep password | cut -f 2 -d :`"

########################################################################
# Variabeln
USERNAME=${1:-$DEFAULT_USERNAME}
PASSWORD=${2:-$DEFAULT_PASSWORD}

PROGNAME=dyndnslogin
COOKIE="${PROGNAME}_cookie"
OUTPUT="${PROGNAME}_output"
DATE=`date +"%y-%m-%d--%H-%M-%S"`

touch $COOKIE
touch $OUTPUT

USERAGENT="Mozilla/5.0"

########################################################################
# Main

curl -k -A $USERAGENT -c $COOKIE https://account.dyn.com | awk -F\' '/multiform/{ print $6 }'
MULTIFORM=`curl -s -k -A $USERAGENT -c $COOKIE https://account.dyn.com | awk -F\' '/multiform/{ print $6 }'`

curl -s -k --location -A "$USERAGENT" -b $COOKIE -c $COOKIE -o $OUTPUT --data "username=$USERNAME&password=$PASSWORD&iov_id=&submit=Log+in&multiform=$MULTIFORM" https://account.dyn.com

if grep -i -E "(Welcome|Hi).*$USERNAME" $OUTPUT > /dev/null 2>&1
then
  echo $DATE: Login successful
else
  echo $DATE: Login failed
  FAILED="true"
fi

cat $OUTPUT > dyndns-logs/$DATE.htm

cp $COOKIE $COOKIE.old
cp $OUTPUT $OUTPUT.old
rm $COOKIE
rm $OUTPUT

if [ "$FAILED" = "true" ]
then
  exit 1
fi

# EOF